### ISSUE TITLE
The List disapears

### ISSUE THREAD

**Issue by vaidares** [andrzejkupczyk/mantis-todolists#22]
Hello,

may be I am to stupid.

I can See the Field "Things To do in an issue.
I can Add the Todo List.
Iff i Update the Issue the List disapears.
It does not matter iff i do it as Admin or Reporter.

How Can I save this my todo List?

My Plugin Conig.
![grafik](https://user-images.githubusercontent.com/64352028/100090154-08384200-2e53-11eb-8c31-66dc80d4fdb8.png)

My System
![grafik](https://user-images.githubusercontent.com/64352028/100089389-e2f70400-2e51-11eb-85b5-7999947a2d7e.png)

**Comment by andrzejkupczyk** [comment]
Hey @vaidares , I'll look into this asap.

**Comment by andrzejkupczyk** [comment]
@vaidares , is this still relevant?

**Comment by kaloczikvn** [comment]
Just installed the 2.1.0 version, the list still disapears after a refresh!

**Comment by andrzejkupczyk** [comment]
Thank you, @kaloczikvn! I will deal with it asap.

**Comment by andrzejkupczyk** [comment]
Phew, this was a nightmare since I couldn't reproduce this myself. @kaloczikvn, screenshots provided by you were very helpful.  

@kaloczikvn @vaidares @King-GO, would you mind to verify whether problem still occurs in the [current release](https://github.com/andrzejkupczyk/mantis-todolists/releases/tag/v2.2.0)?

**Comment by kaloczikvn** [comment]
Just tested and it works without any issues!

Thank you!
